@baseUrl = http://localhost:8000/api

### Get all users 
GET GET {{baseUrl}}/users

### Get all users with archived and join role 
GET {{baseUrl}}/users?archived=true&join=role

### Get all users
GET {{baseUrl}}/users?join=role

### Get a user by id
GET {{baseUrl}}/users/1?join=role

### restore a user 
GET {{baseUrl}}/users/1/restore

### Create a user
POST {{baseUrl}}/users
Content-Type: application/json
Accept: application/json

{
    "first_name": "Shanna223457",
    "last_name": "Breitenberg",
    "email": "velda323457.schaden@example.com",
    "phone_number": "7771239",
    "role_id": 1
}

### Update a user
PUT {{baseUrl}}/users/1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Jean",
    "last_name": "Dupont",
    "phone_number": "+33.1.23.45.67.89"
}

### Delete a user
DELETE {{baseUrl}}/users/1
Accept: application/json

